# =============================================================================
# traceAsthma finalization script
# Run this in RStudio on your Windows desktop, from the traceAsthma/ package
# root directory (i.e. setwd() into the folder that directly contains
# DESCRIPTION before sourcing this script, or open the .Rproj if you have one).
#
# This closes every remaining gap flagged in vignette("clinical-deployment-notes"):
#   1. Installs all Suggests (CRAN + Bioconductor)
#   2. Regenerates NAMESPACE/man/*.Rd from roxygen comments (devtools::document())
#   3. Runs the full test suite for real (testthat)
#   4. Builds all three vignettes for real (knitr/rmarkdown)
#   5. Runs R CMD check --as-cran and reports the result
#
# Expect this to take 15-30 minutes the first time (Bioconductor installs are
# slow) and prompt you a few times to update dependent packages -- answering
# "1" (update all) is the safe default.
# =============================================================================

# --- 0. Prerequisites (Windows-specific) -------------------------------------
# You need Rtools installed and on PATH to compile any package with C/C++/
# Fortran source (several Suggests do: glmnet, xgboost, arrow, etc.).
# Check first:
if (!pkgbuild::has_rtools()) {
  stop(
    "Rtools not detected. Download and install Rtools matching your R version ",
    "from https://cran.r-project.org/bin/windows/Rtools/, restart R, then re-run ",
    "this script. (If pkgbuild isn't installed yet: install.packages('pkgbuild'))"
  )
}

# --- 1. Install tooling and all Suggests --------------------------------------
needed_tooling <- c("devtools", "roxygen2", "testthat", "knitr", "rmarkdown", "BiocManager")
to_install <- setdiff(needed_tooling, rownames(installed.packages()))
if (length(to_install) > 0) install.packages(to_install)

cran_suggests <- c(
  "glmnet", "pROC", "PRROC", "mediation", "boot", "lavaan", "xgboost",
  "randomForest", "rms", "dcurves", "shiny", "writexl", "readxl", "arrow",
  "DBI", "ggplot2"
)
to_install_cran <- setdiff(cran_suggests, rownames(installed.packages()))
if (length(to_install_cran) > 0) install.packages(to_install_cran)

bioc_suggests <- c("viper", "minfi", "sva", "dorothea", "decoupleR")
to_install_bioc <- setdiff(bioc_suggests, rownames(installed.packages()))
if (length(to_install_bioc) > 0) BiocManager::install(to_install_bioc, update = FALSE, ask = FALSE)

cat("\n=== Step 1 complete: all dependencies installed ===\n\n")

# --- 2. Regenerate documentation from roxygen comments ------------------------
# IMPORTANT: the man/*.Rd files and NAMESPACE currently in this package were
# hand-written (roxygen2 was unavailable in the authoring environment) and
# group several functions per file (e.g. qc_functions.Rd covers 4 functions).
# The roxygen comments in R/*.R do NOT use matching @rdname tags, so running
# devtools::document() as-is would generate one new .Rd per function
# alongside the existing hand-written files -- producing duplicate \alias{}
# entries across files, which R CMD check treats as an ERROR.
#
# The safe fix: clear the hand-written NAMESPACE/man/ first, so roxygen2
# generates a clean, internally-consistent set (one .Rd per function/S3-group
# by default, which is perfectly valid for CRAN -- grouping is a style choice,
# not a requirement). This is a one-time transition; after this runs once,
# man/ and NAMESPACE are fully roxygen2-managed going forward.
cat("Clearing hand-written NAMESPACE/man/ before roxygen2 regeneration...\n")
file.remove(list.files("man", pattern = "\\.Rd$", full.names = TRUE))
file.remove("NAMESPACE")

devtools::document()

cat("\n=== Step 2 complete: NAMESPACE and man/*.Rd regenerated by roxygen2 ===\n")
cat("man/ now contains", length(list.files("man", pattern = "\\.Rd$")), "files ",
    "(previously 22 hand-written, grouped files -- roxygen2's default is one ",
    "file per function, so a higher count here is expected and fine).\n\n")

# --- 3. Run the real test suite ------------------------------------------------
test_results <- devtools::test()

cat("\n=== Step 3 complete: test suite executed ===\n")
cat("Review the output above for any FAIL entries.\n\n")

# --- 4. Build all vignettes for real --------------------------------------------
devtools::build_vignettes()

cat("\n=== Step 4 complete: vignettes built ===\n")
cat("Check inst/doc/ for the rendered .html files and open them to review.\n\n")

# --- 5. Full CRAN-style check ----------------------------------------------------
check_result <- devtools::check(
  args = c("--as-cran"),
  build_args = c("--no-build-vignettes")  # already built in step 4
)

cat("\n=== Step 5 complete: R CMD check --as-cran finished ===\n")
cat("Errors:  ", length(check_result$errors), "\n")
cat("Warnings:", length(check_result$warnings), "\n")
cat("Notes:   ", length(check_result$notes), "\n\n")

if (length(check_result$errors) == 0 && length(check_result$warnings) == 0) {
  cat("*** CLEAN CHECK. Package is CRAN-submission-ready (pending manual review ",
      "of the notes above, if any, and reserving a name check via ",
      "https://cran.r-project.org/web/packages/available_packages_by_name.html) ***\n")
} else {
  cat("*** Review the errors/warnings above before proceeding to submission. ***\n")
  print(check_result)
}
